### ISSUE TITLE
Can you provide details of your dataset? Otherwise can't run the program at all

### ISSUE THREAD

**Issue by xugy16** [gingasan/mometas#1]
Our per-training corpus: [a subset of C4](). which subset?

c4/00099.jsonl.gz  what is this?

**Comment by gingasan** [comment]
Thank you for your question. We upload the train data via Google Drive. Please see the update link `a subset of C4`.

00099.jsonl.gz: We use this set for meta-test.

----- 原始邮件 -----
发件人: "xugy16" ***@***.***>
收件人: "gingasan/mometas" ***@***.***>
抄送: "Subscribed" ***@***.***>
发送时间: 星期五, 2023年 6 月 16日 上午 3:36:39
主题: [gingasan/mometas] Can you provide details of your dataset? Otherwise can't run the program at all (Issue #1)

Our per-training corpus: [a subset of C4](). which subset?

c4/00099.jsonl.gz  what is this?

-- 
Reply to this email directly or view it on GitHub:
https://github.com/gingasan/mometas/issues/1
